# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0003_auto_20160808_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
