# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0004_auto_20160808_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cross.Province'),
        ),
        migrations.AlterField(
            model_name='province',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cross.Country'),
        ),
    ]
